version: 2.1


# see https://circleci.com/developer/orbs/orb/circleci/node
# inline orbing it:
# see https://circleci.com/docs/2.0/reusing-config/#writing-inline-orbs
orbs:
  node: circleci/node@4.2.1


# TODO: get the preconfigured setup step to execute `apt install libx11-dev libxkbfile-dev`
# see https://circleci.com/docs/2.0/reusing-config/#steps
# else do this: https://circleci.com/docs/2.0/sample-config/

jobs:  
  test:
    executor:
      name: node/default
      tag: '12.22' 
    parameters:
      setup: 
        default: [apt install libx11-dev libxkbfile-dev]
        type: steps  
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

workflows:
  test_my_app:
    jobs:
      - test
        # context: FusionDB_images