version: 2.1

# docker:
#   - image: cimg/node:12.22-browsers
#     auth:
#       username: duncdrum
#       password: $DOCKER_TMP_PW
#   - image: 'existdb/existdb:latest'
#     auth:
#       username: duncdrum
#       password: $DOCKER_TMP_PW
  # - image: 'existdb/existdb:5.0.0'
  #   auth:
  #     username: duncdrum
  #     password: $DOCKER_TMP_PW
  # - image: 'existdb/existdb:5.2.0'
  #   auth:
  #     username: duncdrum
  #     password: $DOCKER_TMP_PW   


# see https://circleci.com/developer/orbs/orb/circleci/node
# see https://circleci.com/developer/orbs/orb/cypress-io/cypress
# inline orbing it:
# see https://circleci.com/docs/2.0/reusing-config/#writing-inline-orbs
orbs:
  node: circleci/node@4.2.1
  cypress: cypress-io/cypress@1.27.0

# TODO: get the preconfigured setup step to execute `apt install libx11-dev libxkbfile-dev`
# see https://circleci.com/docs/2.0/reusing-config/#steps
# else do this: https://circleci.com/docs/2.0/sample-config/

jobs:  
  test:
    executor:
      name: node/default
      tag: '12.22-browsers'   
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: false
      - run:
          command: |
            sudo apt-get update 
            sudo apt-get install libx11-dev libxkbfile-dev
          name: Install Electron dependencies 
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests

workflows:
  test_my_app:
    jobs:
      - test
        # context: FusionDB_images