version: 2.1

executors:
  context:  FusionDB_images
# TODO(DP): check logs the versions reported on Circle do not match whats in the cimge build logs / description
  node14:
    docker:
      - image: circleci/python:3.9-browsers
        auth:
          username: duncdrum
          password: $DOCKER_TMP_PW

# see https://circleci.com/developer/orbs/orb/circleci/node
# inline orbing it:
# see https://circleci.com/docs/2.0/reusing-config/#writing-inline-orbs
orbs:
  node: circleci/node@4.2.1

jobs:  
  test:
    executor: 'node14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests

workflows:
  test_my_app:
    jobs:
      - test
        # context: FusionDB_images